### ISSUE TITLE
Homework4-Modeling and machine learning.

### ISSUE THREAD

**Issue by JoJoWeixiChen** [JoJoWeixiChen/modeling-and-machine-learning-I-Weixi-Chen#4]
This issue is for the homework4 of class: Modeling and machine learning.

**Comment by TonnarCastellano** [comment]
Ex. 4 is off think about tail action

**Comment by JoJoWeixiChen** [comment]
Hi @TonnarCastellano ,

Thank you for your advice. I updated my homework4.

Weixi

**Comment by TonnarCastellano** [comment]
Pass
